### ISSUE TITLE
Github pages integration.

### ISSUE THREAD

**Issue by ariedov** [pavlospt/Android-Studio-Tips-by-Philippe-Breault#4]
Guys, github pages now just showing up the default mock for them. You just need to merge the master with gh-pages branch and move online..

**Comment by pavlospt** [comment]
I merged the gh-pages into master. What should i do next?

**Comment by ariedov** [comment]
Now I see you've removed the gh-pages branch. Just create one from master and in 10 minutes all will be set up automatically.

**Comment by pavlospt** [comment]
I didn't remove it, i merged it and then unpublished it.

**Comment by ariedov** [comment]
So you need to merge master to gh-pages, not reverse. The point is that gh-pages should have all the code from master to show it online.

**Comment by pavlospt** [comment]
Done
