### ISSUE TITLE
Partial code completion

### ISSUE THREAD

**Issue by karlkovaciny** [pavlospt/Android-Studio-Tips-by-Philippe-Breault#8]
I can't do a pull request for the wiki, but [Partial Code Completion](https://plus.google.com/+PhilippeBreault/posts/PNDwH5cw31w) belongs on the list.

**Comment by pavlospt** [comment]
Will add it ASAP. Thank you

**Comment by pavlospt** [comment]
https://github.com/pavlospt/Android-Studio-Tips-by-Philippe-Breault/wiki/Partial-Code-Completion
